version: "3.9"

services:
  app:
    container_name: divax-i2p-dns-app
    image: divax-i2p-dns-app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - "${PORT}:${PORT}"