version: "3.9"

services:

  divadns:
    container_name: diva-dns
    image: diva-dns:0.5.6-SNAPSHOT
    restart: unless-stopped
    environment:
      - DIVAEXCHANGE_BASEURL=${DIVAEXCHANGE_BASEURL:-http://${BASE_IP:-172.19.72.}21:${PORT:-17468}}
    expose:
      - 8080
    ports:
      - "${HOST_BASE_IP:-127.19.72.}221:8080:8080"
    networks:
      diva-network:
        ipv4_address: ${BASE_IP:-172.19.72.}221

networks:
  diva-network:
    # this is the network of local diva
    # TODO make configurable
    name: network.join.testnet.diva.i2p
#    name: network.testnet3.local
    external: true
